---
- name: BUILD CANDIDATE CONFIGURATIONS
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
    - name: template the config
      template:
        src: "templates/{{ ansible_network_os }}.j2"
        dst: "candidate/configs/{{ inventory_hostname }}-confg"
      delegate_to: localhost
